### ISSUE TITLE
MultiBinary as Action Space not working

### ISSUE THREAD

**Issue by Eslsamu** [hill-a/stable-baselines#1034]
**Describe the bug**
MultiBinary as action space is not working for custom environments.
I tested it for PPO2 and A2C.

**Code example**

```python
import gym
from gym import spaces
import numpy as np
from stable_baselines.common.policies import MlpPolicy
from stable_baselines import PPO2, A2C

class CustomEnv(gym.Env):
  """Custom Environment that follows gym interface"""
  metadata = {'render.modes': ['human']}

  def __init__(self):
    super(CustomEnv, self).__init__()
    # Define action and observation space
    # They must be gym.spaces objects
    # Example when using discrete actions:
    self.action_space = spaces.MultiBinary([3,2])
    # Example for using image as input:
    self.observation_space = spaces.Box(low=0, high=255,
                                        shape=(1,), dtype=np.uint8)

  def step(self, action):
    return np.array([1]), 1.0, True, {}

  def reset(self):
    return np.array([1]) # reward, done, info can't be included

  def render(self, mode='human'):
    pass
  def close (self):
    pass


from stable_baselines.common.env_checker import check_env

env = CustomEnv()
check_env(env)
model = PPO2(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=10000)

obs = env.reset()
for i in range(1000):
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()

```

```bash
sam:pythonProject samuelkopp$ python3 testenv.py
/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
[0] [1]
[1] [1]
[1] [1]
[1] [1]
[1] [1]
[1] [1]
[1] [1]
[1] [1]
[1] [1]
[1] [1]
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "testenv.py", line 37, in <module>
    model = PPO2(MlpPolicy, env, verbose=1)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py", line 97, in __init__
    self.setup_model()
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/stable_baselines/ppo2/ppo2.py", line 131, in setup_model
    n_batch_step, reuse=False, **self.policy_kwargs)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/stable_baselines/common/policies.py", line 661, in __init__
    feature_extraction="mlp", **_kwargs)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/stable_baselines/common/policies.py", line 566, in __init__
    self.pdtype.proba_distribution_from_latent(pi_latent, vf_latent, init_scale=0.01)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/stable_baselines/common/distributions.py", line 268, in proba_distribution_from_latent
    pdparam = linear(pi_latent_vector, 'pi', self.size, init_scale=init_scale, init_bias=init_bias)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/stable_baselines/common/tf_layers.py", line 123, in linear
    weight = tf.get_variable("w", [n_input, n_hidden], initializer=ortho_init(init_scale))
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 721, in _get_single_variable
    shape = tensor_shape.as_shape(shape)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 940, in as_shape
    return TensorShape(shape)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 538, in __init__
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 538, in <listcomp>
    self._dims = [as_dimension(d) for d in dims_iter]
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 479, in as_dimension
    return Dimension(value)
  File "/Users/samuelkopp/.pyenv/versions/3.6.7/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 37, in __init__
    self._value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

```

**System Info**
I installed baselines using pip3 and I tested it using python 3.6.7 with tf 1.8.0 and tf 1.15.

**Comment by araffin** [comment]
Hello,
I'm not sure why you are using `spaces.MultiBinary([3,2])` instead of `spaces.MultiBinary(5)` (or `spaces.MultiBinary(6)` depending on what you want to do) ?

Stable-Baselines only supports the last two cases (which should be equivalent to the first).

**Comment by Eslsamu** [comment]
Hello, 
Well I simply followed the description of the class.

'''
    An n-shape binary space. 
    The argument to MultiBinary defines n, which could be a number or a `list` of numbers.
    
    Example Usage:
    
    >> self.observation_space = spaces.MultiBinary(5)
    >> self.observation_space.sample()
        array([0,1,0,1,0], dtype =int8)
    >> self.observation_space = spaces.MultiBinary([3,2])
    >> self.observation_space.sample()
        array([[0, 0],
               [0, 1],   
               [1, 1]], dtype=int8)
    '''

And yes, you can of course solve it by taking `spaces.MultiBinary(6)` and reshaping it. The description is just misleading.

**Comment by araffin** [comment]
>Well I simply followed the description of the class. It seems to be misleading.

I think they added that feature later... but it does not seems so easy to support with tensorflow 1.
That's why I would recommend you to just use the flatten version.

If you original question was solved, then you can close this issue ;)
