### ISSUE TITLE
Render issue with vecEnv

### ISSUE THREAD

**Issue by araffin** [hill-a/stable-baselines#20]
**Describe the bug**
Error when calling render on vecenv, the bug was not present in version 1.0.7.

**Code example**
```python
from stable_baselines.common.cmd_util import make_atari_env
from stable_baselines.common.vec_env import VecFrameStack
from stable_baselines import A2C

env = make_atari_env('BreakoutNoFrameskip-v4', num_env=9, seed=0)
# Stack 4 frames
env = VecFrameStack(env, n_stack=4)

model = A2C('CnnPolicy', env)
# model = A2C.load("breakout_a2c.pkl")

obs = env.reset()
while True:          
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

Traceback
```
    env.render()
  File "/home/antonin/anaconda3/lib/python3.6/site-packages/stable_baselines/common/vec_env/base_vec_env.py", line 147, in render
    return self.venv.render(**kwargs)
  File "/home/antonin/anaconda3/lib/python3.6/site-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 92, in render
    bigimg = tile_images(imgs)
  File "/home/antonin/anaconda3/lib/python3.6/site-packages/stable_baselines/common/tile_images.py", line 15, in tile_images
    n_images, height, width, n_channels = img_nhwc.shape
ValueError: not enough values to unpack (expected 4, got 1)
```

**System Info**
Describe the characteristic of your environment:
 * Installed via pip (version 1.0.8.rc1)
 * cpu
 * python 3.6
 * tf v 1.8.0

**Comment by hill-a** [comment]
Ok I see why, when comparing 87b8888 to 3ffce2e, we can see I forgot to set the argument for the render function in each sub process, this causes the issue we see here.

**Comment by hn2** [comment]
I am having the same issue:

********** Iteration 0 ************
Traceback (most recent call last):
  File "my_ppo1.py", line 23, in <module>
    model.learn(total_timesteps=TOTAL_TIMESTAMP)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\ppo1\pposgd_simple.py", line 238, in learn
    seg = seg_gen.__next__()
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\trpo_mpi\utils.py", line 100, in traj_segment_generator
    observation, rew, done, _info = env.step(clipped_action[0])
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\base_vec_env.py", line 130, in step
    return self.step_wait()
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\common\base_class.py", line 634, in step_wait
    actions, values, states, information = self.venv.step_wait()
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 36, in step_wait
    self.envs[env_idx].step(self.actions[env_idx])
ValueError: not enough values to unpack (expected 4, got 3)

**Comment by hill-a** [comment]
@hn2, your issue concerns the step of a VecEnv and/or the environment. Not the render function. please use a different issue for this.

**Comment by rporotti** [comment]
Is the bug still there? I have the same error when creating a SubprocVecEnv with a custom environment, using a MlpLstmPolicy. With a MlpPolicy everything works fine.
