### ISSUE TITLE
[bug] set_global_seeds does not work anymore

### ISSUE THREAD

**Issue by doviettung96** [hill-a/stable-baselines#203]
Currently, the function set_global_seeds does not work anymore. The reason might be openai gym has updated (or removed some attributes in gym.spaces). 
This is what I have got when I use it:

Traceback (most recent call last):
  File "PPO2-humanoidflagrunharder-selu.py", line 27, in <module>
    envs = SubprocVecEnv([make_env(env_id, i, seed=10) for i in range(num_env)])
  File "PPO2-humanoidflagrunharder-selu.py", line 27, in <listcomp>
    envs = SubprocVecEnv([make_env(env_id, i, seed=10) for i in range(num_env)])
  File "PPO2-humanoidflagrunharder-selu.py", line 22, in make_env
    set_global_seeds(seed)
  File "/stable-baselines/stable_baselines/common/misc_util.py", line 92, in set_global_seeds
    gym.spaces.prng.seed(seed)
AttributeError: module 'gym.spaces' has no attribute 'prng'

Thanks.

**Comment by araffin** [comment]
Hello,

This was fixed in #185 , please upgrade your SB version.
Next time, don't forget to fill up the template form.

**Comment by doviettung96** [comment]
Thank you. Should I close this issue?

**Comment by araffin** [comment]
If it solves your issue, yes, please.
