### ISSUE TITLE
Unable to use MlpLstmPolicy with TRPO

### ISSUE THREAD

**Issue by HareshMiriyala** [hill-a/stable-baselines#219]
If you have any questions, feel free to create an issue with the tag [question].  
If you wish to suggest an enhancement or feature request, add the tag [feature request].  
If you are submitting a bug report, please fill in the following details.  

**Describe the bug**
`from stable_baselines.common.policies import MlpLstmPolicy
 model = TRPO(MlpLstmPolicy,env,verbose=1)
`

Throws an error saying 

`The given initializer function expects the following args ['shape']`

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed (pip, docker, source, ...) source
 * GPU models and configuration Nvidia 960M
 * Python version 3.6
 * Tensorflow version 1.12
 * Versions of any other relevant libraries

Complete error trace : 

`Traceback (most recent call last):
  File "/home/haresh/PycharmProjects/gazebo_simulations/main.py", line 19, in <module>
    model = TRPO(MlpLstmPolicy,env,verbose=1,tensorboard_log="./ppo2_turtlebot_circuit2/").learn(1000000)
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines/trpo_mpi/trpo_mpi.py", line 102, in __init__
    self.setup_model()
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines/trpo_mpi/trpo_mpi.py", line 127, in setup_model
    None, reuse=False, **self.policy_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines/common/policies.py", line 557, in __init__
    layer_norm=False, feature_extraction="mlp", **_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines/common/policies.py", line 301, in __init__
    layer_norm=layer_norm)
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines/a2c/utils.py", line 199, in lstm
    weight_x = tf.get_variable("wx", [n_input, n_hidden * 4], initializer=ortho_init(init_scale))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 904, in _get_single_variable
    tf_inspect.getargspec(initializer).args)
ValueError: You can only pass an initializer function that expects no arguments to its callable when the shape is not fully defined. The given initializer function expects the following args ['shape']`

**Comment by araffin** [comment]
Duplicated: #140 
It is also documented in the README and in the documentation (See #141 ).
