### ISSUE TITLE
GAIL with CnnPolicy

### ISSUE THREAD

**Issue by XMaster96** [hill-a/stable-baselines#271]
I tried to use `GAIL`, but for some reason it don't work with `CnnPolicy` and an image based `env`. Probably I made a user error, but I can't find it. So it would be nice if someone could tell me what I did wrong.

EDIT: 
according to the documentation GAIL should support all observant types.

code:
```
from stable_baselines import GAIL, DQN
from stable_baselines.gail import ExpertDataset, generate_expert_traj

record_model = DQN('CnnPolicy', 'BreakoutNoFrameskip-v4')
generate_expert_traj(model=record_model, n_episodes=32,
                     save_path='dataset/dummy_BreakoutNoFrameskip-v4',
                     image_folder='record_image_BreakoutNoFrameskip-v4')
del record_model

dataset = ExpertDataset(expert_path='dataset/dummy_BreakoutNoFrameskip-v4.npz', traj_limitation=10, verbose=1)
model = GAIL('CnnPolicy', 'BreakoutNoFrameskip-v4', dataset, verbose=1)
model.learn(total_timesteps=100000)
```

error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 983, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype uint8 for Tensor with dtype float32: 'Tensor("adversary/obfilter/Cast:0", shape=(210, 160, 3), dtype=float32)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project/GAIL_test.py", line 11, in <module>
    model = GAIL('CnnPolicy', 'BreakoutNoFrameskip-v4', dataset, verbose=1)
  File "/usr/local/lib/python3.5/dist-packages/stable_baselines/gail/model.py", line 55, in __init__
    self.setup_model()
  File "/usr/local/lib/python3.5/dist-packages/stable_baselines/gail/model.py", line 73, in setup_model
    self.trpo.setup_model()
  File "/usr/local/lib/python3.5/dist-packages/stable_baselines/trpo_mpi/trpo_mpi.py", line 126, in setup_model
    entcoeff=self.adversary_entcoeff)
  File "/usr/local/lib/python3.5/dist-packages/stable_baselines/gail/adversary.py", line 77, in __init__
    generator_logits = self.build_graph(self.generator_obs_ph, self.generator_acs_ph, reuse=False)
  File "/usr/local/lib/python3.5/dist-packages/stable_baselines/gail/adversary.py", line 121, in build_graph
    obs = (obs_ph - self.obs_rms.mean) / self.obs_rms.std
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 866, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 8318, in sub
    "Sub", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 546, in _apply_op_helper
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Sub' Op has type float32 that does not match type uint8 of argument 'x'.
```

**Comment by araffin** [comment]
Hello,
As stated in the documentation (https://stable-baselines.readthedocs.io/en/master/modules/gail.html):
"Images are not yet handled properly by the current implementation"

**Comment by araffin** [comment]
GAIL may be supported for CNN here: https://github.com/HumanCompatibleAI/imitation (it is a repo notably maintained by @AdamGleave that relies on stable baselines)

I did not have the time to check, but we plan to drop GAIL support for V3 when we migrate to tensorflow 2.

**Comment by AdamGleave** [comment]
`imitation` should support CNN policies and discriminators, although this feature is not well tested, so do let us know if you run into problems.
