### ISSUE TITLE
Error - How to start debug it

### ISSUE THREAD

**Issue by hn2** [hill-a/stable-baselines#380]
Traceback (most recent call last):
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values
         [[{{node loss/VerifyFinite/CheckNumerics}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ppo2.py", line 35, in <module>
    run()
  File "ppo2.py", line 30, in run
    model.learn(total_timesteps=100000)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 326, in learn
    writer=writer, states=mb_states))
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 257, in _train_step
    td_map)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Found Inf or NaN global norm. : Tensor had NaN values
         [[node loss/VerifyFinite/CheckNumerics (defined at C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py:175) ]]

Caused by op 'loss/VerifyFinite/CheckNumerics', defined at:
  File "ppo2.py", line 35, in <module>
    run()
  File "ppo2.py", line 29, in run
    model = PPO2(CustomPolicy, env, gamma=0.99, nminibatches=1, verbose=0, tensorboard_log='tensorboard')
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 93, in __init__
    self.setup_model()
  File "C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 175, in setup_model
    grads, _grad_norm = tf.clip_by_global_norm(grads, self.max_grad_norm)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\ops\clip_ops.py", line 271, in clip_by_global_norm
    "Found Inf or NaN global norm.")
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\ops\numerics.py", line 44, in verify_tensor_all_finite
    return verify_tensor_all_finite_v2(t, msg, name)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\ops\numerics.py", line 62, in verify_tensor_all_finite_v2
    verify_input = array_ops.check_numerics(x, message=message)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 1075, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\hanna\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Found Inf or NaN global norm. : Tensor had NaN values
         [[node loss/VerifyFinite/CheckNumerics (defined at C:\Users\hanna\Anaconda3\lib\site-packages\stable_baselines\ppo2\ppo2.py:175) ]]

**Comment by araffin** [comment]
in agreement with @hill-a , and for the different reasons we mentioned in the mail we sent to you, you are now blocked for 6 months.

(Excerpt of the mail):
You have opened in total 11 issues and we have to constently remind you the basic rules for contributing/asking for help.
The way you keep forgetting our advices is close to mocking. As a result, we decided to block you for 6 months (starting today), so you stop avoiding our warnings.
