### ISSUE TITLE
FetchPickAndPlace can training using DDPG？？

### ISSUE THREAD

**Issue by wxplovehlt** [hill-a/stable-baselines#440]
python -m stable_baselines.ddpg.main
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/noahrl/rl/lib/python3.5/site-packages/stable_baselines/ddpg/main.py", line 139, in <module>
    run(**args)
  File "/home/noahrl/rl/lib/python3.5/site-packages/stable_baselines/ddpg/main.py", line 90, in run
    action_noise=action_noise, buffer_size=int(1e6), verbose=2, **kwargs)
  File "/home/noahrl/rl/lib/python3.5/site-packages/stable_baselines/ddpg/ddpg.py", line 305, in __init__
    self.setup_model()
  File "/home/noahrl/rl/lib/python3.5/site-packages/stable_baselines/ddpg/ddpg.py", line 331, in setup_model
    self.obs_rms = RunningMeanStd(shape=self.observation_space.shape)
  File "/home/noahrl/rl/lib/python3.5/site-packages/stable_baselines/common/mpi_running_mean_std.py", line 21, in __init__
    name="runningsum", trainable=False)
  File "/home/noahrl/rl/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1484, in get_variable
    aggregation=aggregation)
  File "/home/noahrl/rl/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 1234, in get_variable
    aggregation=aggregation)
  File "/home/noahrl/rl/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 538, in get_variable
    aggregation=aggregation)
  File "/home/noahrl/rl/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/home/noahrl/rl/lib/python3.5/site-packages/tensorflow/python/ops/variable_scope.py", line 902, in _get_single_variable
    tf_inspect.getargspec(initializer).args)
ValueError: You can only pass an initializer function that expects no arguments to its callable when the shape is not fully defined. The given initializer function expects the following args ['self', 'shape', 'dtype', 'partition_info', 'verify_shape']

**Comment by araffin** [comment]
Hello,
Please fill the issue template. For env with dict observation space you must use HER.

**Comment by wxplovehlt** [comment]
> Hello,
> Please fill the issue template. For env with dict observation space you must use HER.

thank you！
What is the specific running instruction?

**Comment by araffin** [comment]
I'm sorry but the answer is RTFM: read the documentation first, ask after ;)
