### ISSUE TITLE
[Question] Error after every environment reset

### ISSUE THREAD

**Issue by cli0** [hill-a/stable-baselines#445]
**Describe the bug**
I have designed my own environment and in every environment run (or reset) the environment loads one or more keras tf models and does some feature extraction of them (and additional testing and manipulation on them). However, the agent does not seem to allow for loading neural networks after resetting during the sampling period. I get an error message that I don't quite understand why it happens.

**Code example**
Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

Please use the [markdown code blocks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)
for both code and stack traces.

```python
import gym, os
import tensorflow as tf
import keras
import numpy as np
from env import NNEnv
from stable_baselines import TRPO, DDPG
from stable_baselines.common.policies import MlpPolicy, LstmPolicy, MlpLstmPolicy, FeedForwardPolicy
from stable_baselines.bench import Monitor
from stable_baselines.results_plotter import load_results, ts2xy

log_dir = "logs/"
os.makedirs(log_dir, exist_ok=True)

best_mean_reward, n_steps = -np.inf, 100

#Callback function
def callback(_locals, _globals):
  """
  Callback called at each step (for DQN an others) or after n steps (see ACER or PPO2)
  :param _locals: (dict)
  :param _globals: (dict)
  """
  global n_steps, best_mean_reward
  # Print stats every 1000 calls
  if (n_steps + 1) % 1000 == 0:
      # Evaluate policy training performance
      x, y = ts2xy(load_results(log_dir), 'timesteps')
      if len(x) > 0:
          mean_reward = np.mean(y[-100:])
          print(x[-1], 'timesteps')
          print("Best mean reward: {:.2f} - Last mean reward per episode: {:.2f}".format(best_mean_reward, mean_reward))

          # New best model, you could save the agent here
          if mean_reward > best_mean_reward:
              best_mean_reward = mean_reward
              # Example for saving best model
              print("Saving new best model")
              _locals['self'].save(log_dir + 'best_model.pkl')
  n_steps += 1
  return True


#Custom Policy Network
class CustomPolicy(FeedForwardPolicy):
    def __init__(self, *args, **kwargs):
        super(CustomPolicy, self).__init__(*args, **kwargs,
                                           net_arch=[dict(pi=[1024, 512, 256], vf=[1024, 512, 256])],
                                           feature_extraction="mlp")

####################################################

print("Load original environment.")
env = NNEnv()
print("Set up monitor.")
env = Monitor(env, log_dir, allow_early_resets=True)
print("Initialize the agent...")
agent = TRPO(policy=MlpPolicy, env=env, verbose=1)
print("Training the agent...")
agent.learn(total_timesteps=1000, seed=42, callback=callback)

```

This is how my reset looks like:

```python

    def reset(self):

        K.clear_session()

        self.__init__()

        return self.state

```

This is the errors stack:

```bash
Training the agent...
********** Iteration 0 ************
Optimizing Policy...
sampling
Starting NN extraction subroutine
Traceback (most recent call last):
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    subfeed, allow_tensor=True, allow_operation=False)
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3796, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3875, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("Placeholder:0", shape=(784, 512), dtype=float32) is not an element of this graph.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/clio/Desktop/WorkProject/agent.py", line 68, in <module>
    agent.learn(total_timesteps=1000, seed=42, callback=callback)
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/stable_baselines/trpo_mpi/trpo_mpi.py", line 323, in learn
    seg = seg_gen.__next__()
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/stable_baselines/trpo_mpi/utils.py", line 37, in traj_segment_generator
    observation = env.reset()
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/stable_baselines/bench/monitor.py", line 73, in reset
    return self.env.reset(**kwargs)
  File "/home/clio/Desktop/NNForensics/env.py", line 146, in reset
    self.__init__()
  File "/home/clio/Desktop/WorkProject/env.py", line 22, in __init__
    target_model, global_accuracy, nodes, data, predictions = run_analysis()
  File "/home/clio/Desktop/WorkProject/nn.py", line 20, in run_mode
    model = keras.models.load_model("model/orig_model_2.h5")
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/keras/engine/saving.py", line 420, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/keras/engine/saving.py", line 288, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2471, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/clio/Desktop/WorkProject/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1116, in _run
    'Cannot interpret feed_dict key as Tensor: ' + e.args[0])
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(784, 512), dtype=float32) is not an element of this graph.

Process finished with exit code 1

```

**Comment by Miffyli** [comment]
On the first glance it seems like Keras is trying to load the model to same Tensorflow session that already includes the stable-baselines models and things collide together. Perhaps you have to manually create new session for your Keras models to load/work correctly? [This Tensorflow page on graphs/sessions could help](https://www.tensorflow.org/guide/graphs).

**Comment by araffin** [comment]
Could you please also provide all the relevant packages versions? (keras, tf, sb, os,...)

**Comment by cli0** [comment]
Sorry for the late reply. These are my packages:

Keras | 2.2.4 |
Keras-Applications | 1.0.8 |
Keras-Preprocessing | 1.1.0 |
gym | 0.14.0 | 
h5py | 2.9.0 | 
numpy | 1.17.0 |
stable-baselines | 2.7.0 |
tensorboard | 1.14.0 |
tensorflow | 1.14.0 | 

My OS is Ubuntu 18.04.

The problem arises when the agent is being trained, more precisely when the code tries to reset the environment. I tried to make it so that when reset() is called, the backend is cleared too

```
from keras import backend as K

    def reset(self):

        K.clear_session()

        self.__init__()

        return self.state
```
 but the error persists the same. I did not create every session individually 

> with tf.Session() as sess:

but I am clearing the keras backend sessions and the error still persists. Is the agent doing training in parallel? I.e. simultaneously creating different environments? Or are all environments created sequentially?
