### ISSUE TITLE
Error when trying to load model

### ISSUE THREAD

**Issue by radgordon** [hill-a/stable-baselines#446]
So I am quite new to python and reinforcement learning so I hope I am not making an obvious mistake.

I am currently training a PPO2 agent on a custom environment created using the Gym api. I am using the callback function as seen in the stable-baselines documentation (https://colab.research.google.com/drive/1L_IMo6v0a0ALK8nefZm6PqPSy0vZIWBT) to save the best current model during the training process. 

I have been running my training for some time now and wanted to test the best model so far to see how it is coming along. I copied the "best_model.pkl" file to another computer and attempted to load the model and then run the model on the environment.

When trying to load the model using PPO.load() or if I try to load the parameters using PPO.load_parameters I get this error...

Traceback (most recent call last):
  File "testAgent.py", line 16, in <module>
    model.load_parameters("./trainLogs/best_model.pkl")
  File "/home/radgordon/anaconda3/envs/RL/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 403, in load_parameters
    _, params = BaseRLModel._load_from_file(load_path_or_dict)
  File "/home/radgordon/anaconda3/envs/RL/lib/python3.6/site-packages/stable_baselines/common/base_class.py", line 469, in _load_from_file
    data, params = cloudpickle.load(file)
  File "/home/radgordon/anaconda3/envs/RL/lib/python3.6/site-packages/numpy/random/_pickle.py", line 2, in <module>
    from .philox import Philox
  File "philox.pyx", line 1, in init numpy.random.philox
  File "bit_generator.pyx", line 397, in init numpy.random.bit_generator
TypeError: 'errstate' object is not callable

Any ideas, help or suggestions would be much appreciated. I am able to load a .pkl file from a previous training session without any issues. This has me wondering whether the fact that I copied the .pkl file over while the training was still taking might have affected it.

Might also be worth mentioning that I am using a custom policy which was implemented as detailed in the documentation again.

`class CustomPolicy(FeedForwardPolicy):
          def __init__(self,*args, **kwargs):
                  super(CustomPolicy, self).__init__(*args, **kwargs,act_fun=tf.nn.tanh,net_arch=[dict(pi=[60,40,20],vf=[60,24,5])],feature_extraction="mlp")`

**Comment by radgordon** [comment]
I managed to find the problem. It was an issue with different versions of numpy on the two computers so I guess when the pickle file was unpacked numpy was unable to read the data properly.

This was simply solved by installing the correct version of numpy.
Thanks to anyone who has taken the time to read this.
I will mark this as a closed issue.
