### ISSUE TITLE
Error using custom environment

### ISSUE THREAD

**Issue by venkatesh-chinni** [hill-a/stable-baselines#517]
I have created a custom environment using gym interface. In my agent code when I run

```python
from stable_baselines import ...
from VAV_Env import VAVenv

env = DummyVecEnv([lambda : VAVenv])

```
I get an error
```python
AttributeError: 'NoneType' object has no attribute 'shape'
```
My env code looks like
```python
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 22 22:55:45 2019

@author: VenkateshChinni
"""

import gym
from gym import spaces

import rom_vav_150mm_polyreg as rom
import numpy as np
import random


class VAVenv(gym.Env):
    
    def __init__(self):
        # Zone temperature set point and limits
        self.temp_sp = 24
        self.temp_sp_max = 24.5
        self.temp_sp_min = 23.7
        
        # no; of hours in an episode and time interval for each step
        self.MAXSTEPS = 11
        self.time_interval = 5./60. #in hrs
        
        # constants
        self.zone_volume = 775
        
        # action bounds
        self.cfm_min = 50
        self.cfm_max = 550
        
        # state bounds
        # time, volume, load, sat, rat 
        self.low_state = np.array([1,self.zone_volume,0.3,12,21])
        self.high_state = np.array([11,self.zone_volume,1,20,26])
        
        # continuous actions space
        self.action_space = spaces.Box(low = self.cfm_min, high = self.cfm_max, shape=(1,), dtype=np.float32)
        
        # continuous state space
        self.observation_space = spaces.Box(low=self.low_state, high=self.high_state, dtype=np.float32)
        
        self.reset()
        
    def step(self,action):
        pass

    def reset(self):
        self.state = np.array(0,self.zone_volume,0.5,np.random.uniform(low=12,high=20),
                              np.random.uniform(low = 21,high = 26))
        return np.array(self.state)
        
```
```bash
Traceback (most recent call last):

  File "<ipython-input-5-b7cef7282748>", line 1, in <module>
    env = DummyVecEnv([lambda : VAVenv])

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 23, in __init__
    self.keys, shapes, dtypes = obs_space_info(obs_space)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\common\vec_env\util.py", line 71, in obs_space_info
    shapes[key] = box.shape

AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by araffin** [comment]
Hello, the problem come from the instantiation of your env, you forgot the `()`.
This will work:
```python
env = DummyVecEnv([lambda : VAVenv()])
```

**Comment by Ricahrd-Li** [comment]
Then I get error:
```
    env = DummyVecEnv([lambda : env()])
TypeError: 'SimEnv' object is not callable
```

**Comment by Miffyli** [comment]
@Ricahrd-Li Please follow the examples in documentations (you need to pass a function that creates an environment to DummyVecEnv, not an environment). I also recommend moving on to using [stable-baselines3](https://github.com/DLR-RM/stable-baselines3).
