### ISSUE TITLE
[doc] example may need updating

### ISSUE THREAD

**Issue by rusu24edward** [hill-a/stable-baselines#528]
**Describe the bug**
The [multiprocessing cartpole example](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#multiprocessing-unleashing-the-power-of-vectorized-environments) failed for me when I ran it as is with the following failure:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 261, in main
    old_handlers)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/forkserver.py", line 297, in _serve_one
    code = spawn._main(child_r)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/rusu1/dance/dance_rl/delete_me.py", line 30, in <module>
    env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
  File "/Users/rusu1/.python-virtual-env/dance_venv/lib/python3.7/site-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 90, in __init__
    process.start()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "delete_me.py", line 30, in <module>
    env = SubprocVecEnv([make_env(env_id, i) for i in range(num_cpu)])
  File "/Users/rusu1/.python-virtual-env/dance_venv/lib/python3.7/site-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 95, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

As per the suggestion in the output, I wrapped the code in main check like so:
```python
if __name__ == '__main__':
    env_id = "CartPole-v1"
    ...
```

And it worked out fine for me. I did not have to include the line with `freeze_support()`. So it may be the case that this example in the docs needs to be updated to wrap the code in the main check.

I'm using a virtual environment that I setup specifically for stable baselines, so I don't think I have anything in the environment that is causing this error. However, if you're unable to reproduce, I can provide more environment details.

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed: pip3
 * Python version: python 3.7.4
 * Tensorflow version: 1.14.0
 * Gym: 0.15.3

**Comment by araffin** [comment]
Hello,
thanks for spotting that. In fact, it is documented in the VecEnv page.
There are two solutions :
- change the start_method to fork
- use a DummyVecEnv (usually faster anyway)

we would appreciate a PR that update the doc ;)

**Comment by rusu24edward** [comment]
@araffin Also, it is explained in the docs on the VecEnv page. However, those who go through the docs in order will reach the examples BEFORE they get to the VecEnv page that explains the need.
