### ISSUE TITLE
Unable to save model after calling model.learn

### ISSUE THREAD

**Issue by stephenxudong** [hill-a/stable-baselines#529]
**Describe the bug**
I am unable to save the model per 1000 steps by calling model.learn(total_timesteps=10*100).

**Code example**

```python
import gym
import tensorflow as tf
from stable_baselines.common.policies import FeedForwardPolicy
from stable_baselines import PPO1
import os
import sys
import inspect

arch_str = "32,16"
if arch_str == "":
    arch = []
else:
    arch = [int(layer_width) for layer_width in arch_str.split(",")]
print("Architecture is: %s" % str(arch))

training_sess = None
class MyMlpPolicy(FeedForwardPolicy):

    def __init__(self, sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse=False, **_kwargs):
        super(MyMlpPolicy, self).__init__(sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse, net_arch=[{"pi":arch, "vf":arch}],
                                        feature_extraction="mlp", **_kwargs)
        global training_sess
        training_sess = sess

env = gym.make('CartPole-v0')
gamma=0.99
model = PPO1(MyMlpPolicy, env, verbose=1, schedule='constant', timesteps_per_actorbatch=8192, optim_batchsize=2048, gamma=gamma)

for i in range(0, 10):
    model.learn(total_timesteps=(10*100))
    # want to save model per 10000 steps
    model.save("model-{}".format(i))


```

```bash
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    model.save("model1")
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/stable_baselines/ppo1/pposgd_simple.py", line 360, in save
    self._save_to_file(save_path, data=data, params=params_to_save, cloudpickle=cloudpickle)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/stable_baselines/common/base_class.py", line 532, in _save_to_file
    BaseRLModel._save_to_file_zip(save_path, data, params)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/stable_baselines/common/base_class.py", line 490, in _save_to_file_zip
    serialized_data = data_to_json(data)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/stable_baselines/common/save_util.py", line 52, in data_to_json
    cloudpickle.dumps(data_item)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 1125, in dumps
    cp.dump(obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 489, in save
    self.save_global(obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 877, in save_global
    self.save_dynamic_class(obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 686, in save_dynamic_class
    save(clsdict)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 627, in save_reduce
    save(state)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 627, in save_reduce
    save(state)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 627, in save_reduce
    save(state)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 774, in save_list
    self._batch_appends(obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 798, in _batch_appends
    save(x)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 744, in save_tuple
    save(element)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 627, in save_reduce
    save(state)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 890, in save_instancemethod
    self.save_reduce(types.MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 603, in save_reduce
    save(args)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 729, in save_tuple
    save(element)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 627, in save_reduce
    save(state)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 627, in save_reduce
    save(state)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 627, in save_reduce
    save(state)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 774, in save_list
    self._batch_appends(obj)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 798, in _batch_appends
    save(x)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 744, in save_tuple
    save(element)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 814, in save_dict
    self._batch_setitems(obj.items())
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 840, in _batch_setitems
    save(v)
  File "/Users/stephen/anaconda3/envs/py3.5/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects

```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed **pip**
 * Python version. Python 3.5.6 :: Anaconda, Inc.
 * Tensorflow version. tensorflow  1.8.0
 * Versions of any other relevant libraries. gym 0.15.3

**Additional context**

**Comment by Miffyli** [comment]
Issue lies here:
```
training_sess = None
class MyMlpPolicy(FeedForwardPolicy):

    def __init__(self, sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse=False, **_kwargs):
        super(MyMlpPolicy, self).__init__(sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse, net_arch=[{"pi":arch, "vf":arch}],
                                        feature_extraction="mlp", **_kwargs)
        global training_sess
        # If you store session like this, agent attempts to pickle it
        training_sess = sess
```

You can save tensorflow.Sessions (`sess` object). If you comment out the `trainin_sess = sess` part, then it saves correctly. 

Also: Saving model that way is not optimal and leads to re-initialization of many things. [Try using callbacks instead](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#using-callback-monitoring-training).
