### ISSUE TITLE
Invalid argument: Self-adjoint eigen decomposition was not successful. The input might not be valid

### ISSUE THREAD

**Issue by putraxor** [hill-a/stable-baselines#591]
**Describe the bug**
ACKTR error when trained using GPU

**Code example**
```python
        CSV_IMPUTE = f"data/{asset}_5S_IMPUTED.csv"
        df = pd.read_csv(CSV_IMPUTE, parse_dates=["created_at"])
        binomo = BinomoKontol(df)
        env = DummyVecEnv([lambda: binomo])
        model = ACKTR(MlpPolicy, env, verbose=1, tensorboard_log="./tensorboard/")
        model.set_env(env)
        model.learn(total_timesteps=1_000_000_000, log_interval=10, tb_log_name=asset)
        model.save(brain_name)
```

```bash
---------------------------------
| explained_variance | 0        |
| fps                | 26       |
| nupdates           | 1        |
| policy_entropy     | 2.84     |
| policy_loss        | -0.0206  |
| total_timesteps    | 0        |
| value_loss         | 6.28e+14 |
---------------------------------
Traceback (most recent call last):
  File "/home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Self-adjoint eigen decomposition was not successful. The input might not be valid.
	 [[{{node kfac_apply/cond/SelfAdjointEigV2_17}}]]
	 [[kfac_apply/cond_1/Min_11/Switch/_527]]
  (1) Invalid argument: Self-adjoint eigen decomposition was not successful. The input might not be valid.
	 [[{{node kfac_apply/cond/SelfAdjointEigV2_17}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "binomo_kontol_rl.py", line 139, in <module>
    model.learn(total_timesteps=1_000_000_000, log_interval=10, tb_log_name=asset)
  File "/home/putraxor/.local/lib/python3.7/site-packages/stable_baselines/acktr/acktr.py", line 333, in learn
    writer)
  File "/home/putraxor/.local/lib/python3.7/site-packages/stable_baselines/acktr/acktr.py", line 259, in _train_step
    [self.summary, self.pg_loss, self.vf_loss, self.entropy, self.train_op], td_map)
  File "/home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Self-adjoint eigen decomposition was not successful. The input might not be valid.
	 [[node kfac_apply/cond/SelfAdjointEigV2_17 (defined at /home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[kfac_apply/cond_1/Min_11/Switch/_527]]
  (1) Invalid argument: Self-adjoint eigen decomposition was not successful. The input might not be valid.
	 [[node kfac_apply/cond/SelfAdjointEigV2_17 (defined at /home/putraxor/.local/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.
```

**System Info**
Describe the characteristic of your environment:
 * GPU GeForce RTX 2060
 * Python version 3.7
 * Tensorflow version 1.15

**Comment by Miffyli** [comment]
It is hard to tell where things went wrong with this little information. Can you share e.g. observation and action space of your custom environment? Also is this specific to GPUs or does it also result to same errors ith CPUs? 

Meanwhile you could try simpler algorithms (e.g. PPO, TRPO) to see how well those work. ACKTR contains bunch of these sensitive linear-algebra manipulations which like to throw hissy fits on data they do not like.

**Comment by putraxor** [comment]
when using PPO the loss value is nan, it seems my agent  has something wrong

**Comment by jtromans** [comment]
Were you able to resolve this? What was the issue with your agent? @putraxor

**Comment by hyperactivetimes** [comment]
> when using PPO the loss value is nan, it seems my agent has something wrong

hey there!
i'm trying to solve a problem using advantage actor critic . i faced the same error. were you able to resolve the issue. i would appreciate your guidance if you you could.
