### ISSUE TITLE
Training agents in multiple consoles of spyder.

### ISSUE THREAD

**Issue by venkatesh-chinni** [hill-a/stable-baselines#647]
Hi, I am trying to train an agent in two different consoles of spyder. Training runs in console 1 but in console 2 , it gives an error. I am not sure if its something with stable-baselines or Spyder. 
```
Traceback (most recent call last):

  File "<ipython-input-1-762ab51db582>", line 1, in <module>
    runfile('C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV/VAV_Agent.py', wdir='C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV')

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV/VAV_Agent.py", line 49, in <module>
    log_interval=1, tb_log_name="VAV Logs", reset_num_timesteps=False)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 334, in learn
    obs, returns, masks, actions, values, neglogpacs, states, ep_infos, true_reward = runner.run()

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 465, in run
    actions, values, self.states, neglogpacs = self.model.step(self.obs, self.states, self.dones)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\common\policies.py", line 577, in step
    {self.obs_ph: obs})

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)

InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(8, 5), b.shape=(5, 32), m=8, n=32, k=5
	 [[node model/vf_fc0/MatMul (defined at C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\a2c\utils.py:158) ]]
  (1) Internal: Blas GEMM launch failed : a.shape=(8, 5), b.shape=(5, 32), m=8, n=32, k=5
	 [[node model/vf_fc0/MatMul (defined at C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\a2c\utils.py:158) ]]
	 [[output/add_2/_7]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node model/vf_fc0/MatMul:
 model/vf_fc0/w/read (defined at C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\a2c\utils.py:156)	
 model/flatten/Reshape (defined at C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\common\policies.py:562)

Input Source operations connected to node model/vf_fc0/MatMul:
 model/vf_fc0/w/read (defined at C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\a2c\utils.py:156)	
 model/flatten/Reshape (defined at C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\common\policies.py:562)

Original stack trace for 'model/vf_fc0/MatMul':
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\spyder_kernels\console\__main__.py", line 11, in <module>
    start.main()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\spyder_kernels\console\start.py", line 318, in main
    kernel.start()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\asyncio\base_events.py", line 438, in run_forever
    self._run_once()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\asyncio\base_events.py", line 1451, in _run_once
    handle._run()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tornado\gen.py", line 787, in inner
    self.run()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tornado\gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\ipykernel\kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\ipykernel\kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\IPython\core\interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\IPython\core\interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\IPython\core\interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\IPython\core\interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\IPython\core\interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-762ab51db582>", line 1, in <module>
    runfile('C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV/VAV_Agent.py', wdir='C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV')
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV/VAV_Agent.py", line 42, in <module>
    policy_kwargs=None, full_tensorboard_log=False)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 100, in __init__
    self.setup_model()
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\ppo2\ppo2.py", line 133, in setup_model
    n_batch_step, reuse=False, **self.policy_kwargs)
  File "C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV/VAV_Agent.py", line 35, in __init__
    feature_extraction="mlp")
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\common\policies.py", line 562, in __init__
    pi_latent, vf_latent = mlp_extractor(tf.layers.flatten(self.processed_obs), net_arch, act_fun)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\common\policies.py", line 86, in mlp_extractor
    latent_value = act_fun(linear(latent_value, "vf_fc{}".format(idx), vf_layer_size, init_scale=np.sqrt(2)))
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\stable_baselines\a2c\utils.py", line 158, in linear
    return tf.matmul(input_tensor, weight) + bias
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 2647, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 5925, in mat_mul
    name=name)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

```

If i run again in the same console
```
Reloaded modules: VAV_Env, rom_vav_150mm_polyreg
Traceback (most recent call last):

  File "<ipython-input-2-762ab51db582>", line 1, in <module>
    runfile('C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV/VAV_Agent.py', wdir='C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV')

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/VenkateshChinni/Desktop/RL/stable-baselines/PPO/VAV/VAV_Agent.py", line 18, in <module>
    from VAV_Env import VAVenv

  File "C:\Users\VenkateshChinni\Desktop\RL\stable-baselines\PPO\VAV\VAV_Env.py", line 11, in <module>
    import rom_vav_150mm_polyreg as rom

  File "C:\Users\VenkateshChinni\Desktop\RL\stable-baselines\PPO\VAV\rom_vav_150mm_polyreg.py", line 25, in <module>
    rat_ahu_model.load_weights("VAV_RAT.h5")

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\keras\engine\saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\keras\backend\tensorflow_backend.py", line 2470, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\keras\backend\tensorflow_backend.py", line 199, in get_session
    [tf.is_variable_initialized(v) for v in candidate_vars])

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 950, in run
    run_metadata_ptr)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
    run_metadata)

  File "C:\Users\VenkateshChinni\.conda\envs\py36\lib\site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)

InternalError: GPU sync failed
```

**Comment by venkatesh-chinni** [comment]
Hi , what information should I share so that it will be helpful?

**Comment by araffin** [comment]
Just fill *completely* the issue template ;)
but it looks like a bug from a custom environment, did you try with a normal one? (included in gym)

**Comment by venkatesh-chinni** [comment]
**System Info**
 * installed using pip 
 * GPU models and configuration - NVIDIA Quadro P600 , VRAM - 4GB
 * Python version - 3.6
 * Tensorflow version - 1.14
* Using  a custom environment

**Comment by Miffyli** [comment]
As arrafin mentioned, you should try the same setup with premade/"normal" environments like the ones in Gym. The error seems to stem from your environment and Tensorflow. I would also advice running the code outside any notebooks/Jupyter kernels (i.e. just call `python [your script file]`), as these add additional layer of problems to deal with.

**Comment by venkatesh-chinni** [comment]
I did not face this issue when I was using just tensorflow. I was able to train agents in multiple consoles of spyder. Recently I have installed tensorflow-gpu and since then I am facing this issue. So , I guess its because of tensorflow-gpu. Is there a way I can make stable-baselines use only ternsorflow but not tensorflow-gpu , which is by default picked up?

**Comment by Miffyli** [comment]
Both tensorflow-gpu and tensorflow install under name `tensorflow`, so (by default) you will only use one. However you could try forcing code not to use a GPU. Unfortunately on Windows this is not as easy as on Linux where you can set environment variable `CUDA_VISIBLE_DEVICES=""`.

You can modify the config in [this](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/tf_util.py#L58) function to force the GPU with

```
tf_config = tf.ConfigProto(
        allow_soft_placement=True,
        inter_op_parallelism_threads=num_cpu,
        intra_op_parallelism_threads=num_cpu,
        device_count={"GPU": 0}
)
```

**Comment by araffin** [comment]
closing this issue because related to tf only
