### ISSUE TITLE
env.render() does not work in A2C code from stable_baselines documentation

### ISSUE THREAD

**Issue by erikforss1905** [hill-a/stable-baselines#67]
[help wanted]
**Describe the bug**
My issue/question is regarding the [example code in the documentation for A2C](https://stable-baselines.readthedocs.io/en/master/modules/a2c.html#example).
When I try to run it, it seems to work fine. Model is trained, saved and restored.
But when env.render() is called, I get an EOFError.

Also, when I try to call env.close() afterwards I get another error.
I understand it has something to do with the multiprocessing module.

**But why is it not possible for me to render in the first place?**
Without render() it seems to work fine the model plays CartPole. I tested with Print(obs, rewards, dones) which worked.

**Code example**
Stacktrace for EOFError when calling env.render():
```
File "<ipython-input-2-6953c62eb323>", line 1, in <module>
    runfile('/Users/erik/Documents/Thesis/03 Arbeitsordner/01 Code/ETA-Brain/erik/easy_agents/minitest.py', wdir='/Users/erik/Documents/Thesis/03 Arbeitsordner/01 Code/ETA-Brain/erik/easy_agents')

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/erik/Documents/Thesis/03 Arbeitsordner/01 Code/ETA-Brain/erik/easy_agents/minitest.py", line 29, in <module>
    env.render()

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/site-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 93, in render
    imgs = [pipe.recv() for pipe in self.remotes]

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/site-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 93, in <listcomp>
    imgs = [pipe.recv() for pipe in self.remotes]

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError

EOFError
```

Stacktrace for env.close()
```
env.close()
Traceback (most recent call last):

  File "<ipython-input-18-1baceacf4cb1>", line 1, in <module>
    env.close()

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/site-packages/stable_baselines/common/vec_env/subproc_vec_env.py", line 83, in close
    remote.send(('close', None))

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)

  File "/Users/erik/anaconda3/envs/tensorflow/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)

BrokenPipeError: [Errno 32] Broken pipe
```

**System Info**
Describe the characteristic of your environment:
 * library was installed using pip
 * working on Mac, no GPU
 * Python version = 3.6.5, installed using anaconda
 * Tensorflow version = 1.7.0, installed in a anaconda virtual env

**Comment by araffin** [comment]
Hello,

What version of stable-baselines are you using ? What is your gym version ?

Could you try with n_cpu=1 and also with a DummyVecEnv ?

```python
import gym

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import SubprocVecEnv, DummyVecEnv
from stable_baselines import A2C

# multiprocess environment
n_cpu = 1
env = DummyVecEnv([lambda: gym.make('CartPole-v1') for i in range(n_cpu)])

model = A2C(MlpPolicy, env, verbose=1)
model.learn(total_timesteps=25000)
model.save("a2c_cartpole")

del model # remove to demonstrate saving and loading

model = A2C.load("a2c_cartpole")

obs = env.reset()
while True:
    action, _states = model.predict(obs)
    obs, rewards, dones, info = env.step(action)
    env.render()
```

**Comment by erikforss1905** [comment]
Hey, thanks for the fast response.
I actually tried already with n_cpu = 1 before posting here.

Changing to DummyVecEnv solved the issue for me!

Thanks a lot!

If you still have the time to answer another question:
Why didn't it work with the `SubprocEnv`? 
If the environment's outputs are only arrays like in CartPole, the `DummyVecEnv`should always be sufficient, right?

**Comment by araffin** [comment]
Hello,
I'm not sure why, but for instance, SubprocEnv does not work on Windows. For mac os, I don't know, but apparently for rendering, there are issues. The only environment where there is no issue at all is linux.

I recommend you using SubprocEnv for training (it will allow you to multiprocess training) and then, if you want to render the learned policy, use a DummyVecEnv with only one env.
DummyVecEnv does only makes sense for n_cpu=1 (even so it works for n_cpu >=1).
