### ISSUE TITLE
HER+DDPG not working with custom env

### ISSUE THREAD

**Issue by tirafesi** [hill-a/stable-baselines#743]
When running HER + DDPG on a custom env I get the following error:

```
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    reset_num_timesteps = False
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/her/her.py", line 113, in learn
    replay_wrapper=self.replay_wrapper)
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/ddpg/ddpg.py", line 1006, in learn
    stats = self._get_stats()
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/ddpg/ddpg.py", line 740, in _get_stats
    env=self._vec_normalize_env)
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/her/replay_buffer.py", line 83, in sample
    return self.replay_buffer.sample(*args, **kwargs)
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/buffers.py", line 142, in sample
    idxes = [random.randint(0, len(self._storage) - 1) for _ in range(batch_size)]
  File "/home/tirafesi/.local/lib/python3.6/site-packages/stable_baselines/common/buffers.py", line 142, in <listcomp>
    idxes = [random.randint(0, len(self._storage) - 1) for _ in range(batch_size)]
  File "/usr/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
```

I tried using `BitFlippingEnv` instead of my custom env and it worked fine. In the following code, if I replace `DDPG` with `SAC` it also works fine. I'm guessing there's something I need to do to make my environment compatible with `DDPG`?

```python3
from my_custom_env import MyCustomEnv

from stable_baselines import HER, SAC, DDPG
from stable_baselines.common.callbacks import CheckpointCallback

# training env
env = MyCustomEnv()

model = HER(
	policy = 'MlpPolicy',
	env = env,
	model_class = DDPG,
	verbose = 1,
	tensorboard_log = "logs/"
)

# train
model.learn(
	total_timesteps = 1000,
	callback = CheckpointCallback(save_freq = 100, save_path = "logs/"),
	log_interval = 1,
	reset_num_timesteps = False
)

env.close()
```

**Comment by Miffyli** [comment]
@araffin Can you comment on this one? As far I understood, it should not require additional modifications, but hard to say anything further than that with this error message.

**Comment by araffin** [comment]
Did you use the env checker?

**Comment by tirafesi** [comment]
> Did you use the env checker?

```
> python
>>> from my_custom_env import MyCustomEnv
>>> from stable_baselines.common.env_checker import check_env
>>> env = MyCustomEnv()
/usr/local/lib/python3.6/dist-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
>>> check_env(env)
/home/guest/.local/lib/python3.6/site-packages/stable_baselines/common/env_checker.py:210: UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html
  warnings.warn("We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) "
```

**Comment by araffin** [comment]
I think what may happened, but I thought i fixed it in the past. It is trying to sample the replay buffer which is empty, but normally we do a `can_sample()` check before...

**Comment by araffin** [comment]
In fact, the error is the same as https://github.com/hill-a/stable-baselines/issues/353

**Comment by araffin** [comment]
I see the bug comes from `_get_stats`, we would appreciate a PR that do a `can_sample` check before it is called (line 739 of ddpg.py)

**Comment by tirafesi** [comment]
That worked, thanks!

I can make the PR today, but I have a question regarding the changelog file: where should I write the changes? (since Release 2.10.0  already happened on 2020-03-11)

**Comment by araffin** [comment]
You should create a new pre-release with empty sections, If you are unsure of what to do, I will do it for you ;)
