### ISSUE TITLE
How to Render non Image in SubprocVecEnv [Question]

### ISSUE THREAD

**Issue by toksis** [hill-a/stable-baselines#753]
How to render a non image in SubprocVecEnv?

I have this code on my Environment.

```python

    def render(self, mode='human', close=False):
        # Render the environment to the screen
        profit = self.net_worth - INITIAL_ACCOUNT_BALANCE

        print(f'Step: {self.current_step}')
        print(f'Balance: {self.balance}')
        print(
            f'Shares held: {self.shares_held} (Total sold: {self.total_shares_sold})')
        print(
            f'Avg cost for held shares: {self.cost_basis} (Total sales value: {self.total_sales_value})')
        print(
            f'Net worth: {self.net_worth} (Max net worth: {self.max_net_worth})')
        print(f'Profit: {profit}')
```
Render works in DummyVecEnv.

But on the SubprocVecEnv, I have this error.

```python
Traceback (most recent call last):
  File "TrainStocks.py", line 52, in <module>
    main()
  File "TrainStocks.py", line 46, in main
    env.render(mode ='human')
  File "C:\anaconda\envs\StableBaselines\lib\site-packages\stable_baselines\common\vec_env\base_vec_env.py", line 171, in render
    bigimg = tile_images(imgs)
  File "C:\anaconda\envs\StableBaselines\lib\site-packages\stable_baselines\common\tile_images.py", line 15, in tile_images
    n_images, height, width, n_channels = img_nhwc.shape
ValueError: not enough values to unpack (expected 4, got 1)
```

Sorry I don't know how to create a tag.

Thanks,
vic

**Comment by araffin** [comment]
Hello,

You custom gym env does not follow the interface (the `mode="human"` and `mode="rgb_array"` are meant for images).
In your case, you should rename it to `print_step` (or something different) and use `env_method()` to call that function (cf doc).

**Comment by toksis** [comment]
Thank you,

I followed your advice and it is working.

On the Environment, replace render to print_step()

```python
 def print_step(self, mode='human', close=False):
        # Render the environment to the screen
        profit = self.net_worth - INITIAL_ACCOUNT_BALANCE

        print(f'Step: {self.current_step}')
        print(f'Balance: {self.balance}')
        print(
            f'Shares held: {self.shares_held} (Total sold: {self.total_shares_sold})')
        print(
            f'Avg cost for held shares: {self.cost_basis} (Total sales value: {self.total_sales_value})')
        print(
            f'Net worth: {self.net_worth} (Max net worth: {self.max_net_worth})')
        print(f'Profit: {profit}')
```

Then on the main, instead of env.render replace it with env_method like this.

```python
 for i in range(2000):
        action, _states = model.predict(obs)
        obs, rewards, done, info = env.step(action)
        env.env_method(method_name='print_step')
```
