### ISSUE TITLE
info['TimeLimit.truncated'] in time_limit.py reports  IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices. [question]

### ISSUE THREAD

**Issue by WeiJieQiang** [hill-a/stable-baselines#763]
**Important Note: We do not do technical support, nor consulting** and don't answer personal questions per email.

If you have any questions, feel free to create an issue with the tag [question].  
If you wish to suggest an enhancement or feature request, add the tag [feature request].  
If you are submitting a bug report, please fill in the following details.

**Describe the bug**
The error pops up when model.learn(total_timesteps=400) is called.  I did print out info and it is an empty numpy.ndarray. 

```python
import gym
import numpy as np
import gym_environment
from stable_baselines.ddpg.policies import MlpPolicy
from stable_baselines.common.noise import NormalActionNoise, OrnsteinUhlenbeckActionNoise, AdaptiveParamNoiseSpec
from stable_baselines import DDPG

env = gym.make('gym_environment:FullFilterEnv-v0')

# the noise objects for DDPG
n_actions = 13 # hard coded for the env
param_noise = None
action_noise = OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=float(0.5) * np.ones(n_actions))

model = DDPG(MlpPolicy, env, verbose=1, action_noise=action_noise)
model.learn(total_timesteps=400)

```

```bash
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    model.learn(total_timesteps=400)
  File "/Users/eejiiew/Projects/filters-auto-tuning/venv-test/lib/python3.7/site-packages/stable_baselines/ddpg/ddpg.py", line 894, in learn
    new_obs, reward, done, info = self.env.step(unscaled_action)
  File "/Users/eejiiew/Projects/filters-auto-tuning/venv-test/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 23, in step
    info['TimeLimit.truncated'] = not done
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**System Info**
Describe the characteristic of your environment:
 * macOS
 * GPU models and configuration
 * Python 3.7
 * Tensorflow 1.14
 * stable-baselines 2.10.0

**Comment by araffin** [comment]
Hello,
Did you check your custom env using the env checker? (cf doc)

**Comment by WeiJieQiang** [comment]
Thanks for the reply. I am checking this. @araffin

**Comment by WeiJieQiang** [comment]
env.check gives me the following warnings. 

```bash
 UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html
  warnings.warn("We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) "
```

I saw in another [issue](https://github.com/hill-a/stable-baselines/issues/743) the problem happened. Is is solved in the latest version? Or the solution is 
```Python
stats = self.can_sample()._get_stats()
```
?

The next warning is 
```bash
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    check_env(env)
  File "/Users/eejiiew/Projects/filters-auto-tuning/venv-test/lib/python3.7/site-packages/stable_baselines/common/env_checker.py", line 214, in check_env
    _check_returned_values(env, observation_space, action_space)
  File "/Users/eejiiew/Projects/filters-auto-tuning/venv-test/lib/python3.7/site-packages/stable_baselines/common/env_checker.py", line 99, in _check_returned_values
    _check_obs(obs, observation_space, 'reset')
  File "/Users/eejiiew/Projects/filters-auto-tuning/venv-test/lib/python3.7/site-packages/stable_baselines/common/env_checker.py", line 89, in _check_obs
    "method does not match the given observation space".format(method_name))
AssertionError: The observation returned by the `reset()` method does not match the given observation space
```

Looking forward to the suggestions.

**Comment by araffin** [comment]
It's not a warning, and the error message is quite explicit ;)
This issue does not seems related to SB, closing this one then.

**Comment by WeiJieQiang** [comment]
Thanks for the help. All the warnings /errors are fixed and the ddpg model is running. Only the first UserWarning is still there.
