### ISSUE TITLE
SAC can't setup model without env whereas TD3/DDPG can

### ISSUE THREAD

**Issue by Solliet** [hill-a/stable-baselines#764]
**Describe the bug**
Minor issue. SAC can't initialize the model without the environment, but TD3/DDPG can do it.

**Code example**
```python
env = gym.make('MountainCarContinuous-v0')
agent = sb.TD3('MlpPolicy', None, _init_setup_model=False)
agent.action_space = env.action_space
agent.observation_space = env.observation_space
agent.setup_model()

agent = sb.DDPG('MlpPolicy', None, _init_setup_model=False)
agent.action_space = env.action_space
agent.observation_space = env.observation_space
agent.setup_model()

env = gym.make('MountainCarContinuous-v0')
agent = sb.SAC('MlpPolicy', None, _init_setup_model=False)
agent.action_space = env.action_space
agent.observation_space = env.observation_space
agent.setup_model()
```

```bash
Traceback (most recent call last):
  File "hm/HAC/hac.py", line 109, in <module>
    agent.setup_model()
  File "/Users/stelios/Documents/stable-baselines/stable_baselines/sac/sac.py", line 181, in setup_model
    self.target_entropy = -np.prod(self.env.action_space.shape).astype(np.float32)
AttributeError: 'NoneType' object has no attribute 'action_space'
```

I am suggesting this more for consistency between the the algorithms. The solution is just to replace:

```python
self.target_entropy = -np.prod(self.env.action_space.shape).astype(np.float32)
```
with
```python
self.target_entropy = -np.prod(self.action_space.shape).astype(np.float32)
```

**Comment by araffin** [comment]
Hello,
Why would you even do that?

**Comment by Solliet** [comment]
Hierarchical/multi agents. Removes the need to override both the `setup_model` and the `learn` functions. However, if you want, I can change it so that TD3/DDPG use `self.env.actionspace`. It's more for consistency tbh.

**Comment by araffin** [comment]
> It's more for consistency tbh.

Ok, then, please change it to `self.action_space` for consistency.
