### ISSUE TITLE
[question] The observation returned by `reset()` method must be an int

### ISSUE THREAD

**Issue by CesMak** [hill-a/stable-baselines#777]
Hey there,

I wonder why I get this error 

**Gym (snippet)**
```python
class WitchesEnv(gym.Env):
    metadata = {'render.modes': ['human']}
    def __init__(self):
        self.seed()
        self.action_space = gym.spaces.Discrete(60)
        self.observation_space = gym.spaces.Discrete(240)
    def reset(self):
        self.my_game.reset_game()
        self.playUnitlAI()
        state = self.my_game.getState()
        print("INSIDE RESET!!!","\n\n\n")
        print(type(state.flatten()), state.flatten().shape, state.flatten())
        return state.flatten()
```

**Test env**
```python
import gym
import gym_witches

from stable_baselines.common.env_checker import check_env
from stable_baselines import DQN, PPO2, A2C, ACKTR

env = gym.make("Witches-v0")
check_env(env, warn=True)
```

**Error**
```
<class 'numpy.ndarray'> (240,) [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1.
 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1.
 1. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0.]
Traceback (most recent call last):
  File "ppo_baselines.py", line 21, in <module>
    check_env(env, warn=True)
  File "/home/markus/Documents/06_Software_Projects/mcts/mcts_env/lib/python3.6/site-packages/stable_baselines/common/env_checker.py", line 214, in check_env
    _check_returned_values(env, observation_space, action_space)
  File "/home/markus/Documents/06_Software_Projects/mcts/mcts_env/lib/python3.6/site-packages/stable_baselines/common/env_checker.py", line 99, in _check_returned_values
    _check_obs(obs, observation_space, 'reset')
  File "/home/markus/Documents/06_Software_Projects/mcts/mcts_env/lib/python3.6/site-packages/stable_baselines/common/env_checker.py", line 83, in _check_obs
    assert isinstance(obs, int), "The observation returned by `{}()` method must be an int".format(method_name)
AssertionError: The observation returned by `reset()` method must be an int
```

**Comment by Miffyli** [comment]
As explained by the error, you observations have to be of "int" type, but they are floating point numbers (the "." in the end). Do `state.flatten().astype(np.int)` in the `reset` function.

**Comment by araffin** [comment]
In fact, I think there is a misunderstanding about what a `Discrete` space is.
In your case, it seems that you have rather a `MultiBinary` env.
