### ISSUE TITLE
Cannot feed value in pretrain with Cnn policy

### ISSUE THREAD

**Issue by Solliet** [hill-a/stable-baselines#786]
**Describe the bug**
I am trying to Pretrain a CNN policy but pretrain doesn't accept images.

**Code example**

```python
import stable_baselines as sb
from hm.tower import ObstacleTowerEnv
from stable_baselines.gail import ExpertDataset

env = ObstacleTowerEnv()
m = sb.PPO2('CnnPolicy', env)
demo = ExpertDataset("demo.npz")
m.pretrain(demo)
```

```bash
actions (7251,)
obs (7251,)
rewards (7251,)
episode_returns (14,)
episode_starts (7251,)
Total trajectories: -1
Total transitions: 7251
Average returns: 6.835714324776616
Std for returns: 9.59170832043877
Traceback (most recent call last):
  File "/Users/stelios/anaconda3/envs/thesis/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/stelios/anaconda3/envs/thesis/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/stelios/Documents/cs-401-code/hm/sb/runs.py", line 8, in <module>
    m.pretrain(demo)
  File "/Users/stelios/Documents/stable-baselines/stable_baselines/common/base_class.py", line 352, in pretrain
    train_loss_, _ = self.sess.run([loss, optim_op], feed_dict)
  File "/Users/stelios/anaconda3/envs/thesis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/Users/stelios/anaconda3/envs/thesis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1156, in _run
    (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (64,) for Tensor 'pretrain/ExpandDims:0', which has shape '(?, 1)'

```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed: pip
 * GPU models and configuration: None
 * Python version: 3.7.6
 * Tensorflow version: 1.15.0

**Additional context**
Note: The demonstrations for ObstacleTower were in unity format and I parsed them to create the demo file.

**Comment by Miffyli** [comment]
The [example code](https://stable-baselines.readthedocs.io/en/master/guide/pretrain.html) with Atari Breakout-v0 on stable-baselines v2.10.0 and Ubuntu 18.04 works for me. Make sure your data is formatted in right way.

**Comment by Solliet** [comment]
Oh right, yes, it should have been `(64,1)` instead of `(64,)`, hence why it expects `(?, 1)`. It works now. Sorry my bad.
