### ISSUE TITLE
can't pickle _thread.RLock objects while saving model

### ISSUE THREAD

**Issue by amirhagai** [hill-a/stable-baselines#868]
hi!
TensorFlow version - 1.15.0
python - 3.6.10
I install the package using pip install stable-baselines[mpi] in my conda env.

the code I try to run is:

class MyMlpPolicy(FeedForwardPolicy):

    def __init__(self, sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse=False, **_kwargs):
        super(MyMlpPolicy, self).__init__(sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse, net_arch=[{"pi":arch, "vf":arch}],
                                        feature_extraction="mlp", **_kwargs)
        global training_sess
        training_sess = sess

env = gym.make('PccNs-v0')

gamma = arg_or_default("--gamma", default=0.99)
model = PPO1(MyMlpPolicy, env, verbose=1, schedule='constant', timesteps_per_actorbatch=8192, optim_batchsize=2048, gamma=gamma)
model.learn(total_timesteps=(1600 * 410))
model.save("my_model")

but the save fails when data_to_json try to serialize the policy.

adding trace

Traceback (most recent call last):
  File "C:/Users/me/Desktop/PCC-RL-master/src/gym/stable_solve.py", line 60, in <module>
    model.save("C:\\Users\\me\\Desktop\\PCC-RL-master\\src\\gym\\model_aurora")
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\stable_baselines\ppo1\pposgd_simple.py", line 371, in save
    self._save_to_file(save_path, data=data, params=params_to_save, cloudpickle=cloudpickle)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\stable_baselines\common\base_class.py", line 604, in _save_to_file
    BaseRLModel._save_to_file_zip(save_path, data, params)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\stable_baselines\common\base_class.py", line 562, in _save_to_file_zip
    serialized_data = data_to_json(data)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\stable_baselines\common\save_util.py", line 52, in data_to_json
    cloudpickle.dumps(data_item)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\cloudpickle\cloudpickle.py", line 1148, in dumps
    cp.dump(obj)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\cloudpickle\cloudpickle.py", line 491, in dump
    return Pickler.dump(self, obj)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 409, in dump
    self.save(obj)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 490, in save
    self.save_global(obj)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\cloudpickle\cloudpickle.py", line 899, in save_global
    self.save_dynamic_class(obj)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\cloudpickle\cloudpickle.py", line 708, in save_dynamic_class
    save(clsdict)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\ame\Anaconda3\envs\PCC\lib\site-packages\cloudpickle\cloudpickle.py", line 566, in save_function
    return self.save_function_tuple(obj)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\site-packages\cloudpickle\cloudpickle.py", line 780, in save_function_tuple
    save(state)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Usersme\Anaconda3\envs\PCC\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Usersme\Anaconda3\envs\PCC\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Usersme\Anaconda3\envs\PCC\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 634, in save_reduce
    save(state)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 634, in save_reduce
    save(state)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\me\Anaconda3\envs\PCC\lib\pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.RLock objects

Thanks!

**Comment by Miffyli** [comment]
Could you try same with standard MlpPolicy or without the `global training_session` part? It seems like something that can not be pickled is tried to be pickled. This includes e.g. TF sessions.

**Comment by amirhagai** [comment]
works after the deletion. 
Thanks a lot!!!!
