### ISSUE TITLE
[help wanted] Multiple Environments with Unity MLagents

### ISSUE THREAD

**Issue by seboz123** [hill-a/stable-baselines#883]
Hi,

I am trying to combine the algorithms of this repo with https://github.com/Unity-Technologies/ml-agents .
I created an environement, and used their python API, which contains a wrapper to gym. When I then try to create a SubprocVecEnv with the environements, I get the following Error:

```2020-06-05 18:23:45 INFO [environment.py:111] Connected to Unity environment with package version 1.0.0-preview and communication version 1.0.0
2020-06-05 18:23:46 INFO [environment.py:342] Connected new brain:
Brain?team=0
2020-06-05 18:23:48 INFO [environment.py:111] Connected to Unity environment with package version 1.0.0-preview and communication version 1.0.0
2020-06-05 18:23:49 INFO [environment.py:342] Connected new brain:
Brain?team=0
Traceback (most recent call last):
  File "C:/Users/Sebastian/Desktop/RLUnity/python/test.py", line 46, in <module>
    env = SubprocVecEnv([env1 , env2])
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\stable_baselines\common\vec_env\subproc_vec_env.py", line 93, in __init__
    process.start()
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\stable_baselines\common\vec_env\base_vec_env.py", line 331, in __getstate__
    return cloudpickle.dumps(self.var)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\cloudpickle\cloudpickle.py", line 1148, in dumps
    cp.dump(obj)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\cloudpickle\cloudpickle.py", line 491, in dump
    return Pickler.dump(self, obj)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
2020-06-05 18:23:49 INFO [environment.py:498] Environment shut down with return code 0 (CTRL_C_EVENT).
2020-06-05 18:23:49 INFO [environment.py:498] Environment shut down with return code 0 (CTRL_C_EVENT).

Process finished with exit code 1

```
This is the code I am trying to run:

```python
import tensorflow as tf
from mlagents_envs.environment import UnityEnvironment

from stable_baselines.common.policies import MlpPolicy
from stable_baselines.common.vec_env import DummyVecEnv, SubprocVecEnv
from stable_baselines import PPO2
from gym_unity.envs import UnityToGymWrapper
from mlagents_envs.side_channel.engine_configuration_channel import EngineConfig, EngineConfigurationChannel

try:
    from mpi4py import MPI
    print("MPI found!")
except ImportError:
    print("No MPI")
    MPI = None
MPI = None

engine_configuration_channel = EngineConfigurationChannel()
engine_configuration_channel.set_configuration_parameters(time_scale = 10.0)

unityEnv1 = UnityEnvironment(worker_id=0, file_name="C:/Users/Sebastian/Desktop/RLUnity/ml-agents/exe2/RLproject", no_graphics=False ,seed=1, side_channels = [engine_configuration_channel])
env1 = UnityToGymWrapper(unityEnv1, 0, False)
unityEnv2 = UnityEnvironment(worker_id=1, file_name="C:/Users/Sebastian/Desktop/RLUnity/ml-agents/exe2/RLproject", no_graphics=False ,seed=1, side_channels = [engine_configuration_channel])
env2 = UnityToGymWrapper(unityEnv2, 0, False)

env = SubprocVecEnv([env1 , env2])

```

```bash
Traceback (most recent call last): File ...

```

**System Info**
Describe the characteristic of your environment:
 * Describe how the library was installed pip
 * GPU models and configuration rtx 2070
 * Python version 3.7.7
 * Tensorflow version 1.14
 * Versions of any other relevant libraries

**Additional context**

**Comment by araffin** [comment]
Hello,

Did you try with a `DummyVecEnv` instead?

**Comment by araffin** [comment]
You second solution is still not returning the right thing (please read the doc).
And what was the result with `DummyVecEnv`?

**Comment by seboz123** [comment]
Sorry about that. I changed it according to the example and tried it with `DummyVecEnv`. In both cases I get the Error:

```
E0606 00:24:51.714000000 21420 src/core/ext/transport/chttp2/server/insecure/server_chttp2.cc:40] {"created":"@1591395891.714000000","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":397,"referenced_errors":[{"created":"@1591395891.714000000","description":"Failed to add port to server","file":"src/core/lib/iomgr/tcp_server_windows.cc","file_line":512,"referenced_errors":[{"created":"@1591395891.714000000","description":"OS Error","file":"src/core/lib/iomgr/tcp_server_windows.cc","file_line":203,"os_error":"Unable to retrieve error string","syscall":"bind","wsa_error":10048}]}]}
2020-06-06 00:25:51 INFO [environment.py:500] Environment timed out shutting down. Killing...
Traceback (most recent call last):
  File "C:/Users/Sebastian/Desktop/RLUnity/python/test.py", line 56, in <module>
    env = DummyVecEnv ([create_env(i) for i in range(2)])
  File "C:/Users/Sebastian/Desktop/RLUnity/python/test.py", line 56, in <listcomp>
    env = DummyVecEnv ([create_env(i) for i in range(2)])
  File "C:/Users/Sebastian/Desktop/RLUnity/python/test.py", line 46, in create_env
    return _init(id)
  File "C:/Users/Sebastian/Desktop/RLUnity/python/test.py", line 43, in _init
    no_graphics=False, seed=1, side_channels=[engine_configuration_channel])
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\mlagents_envs\environment.py", line 213, in __init__
    aca_output = self.send_academy_parameters(rl_init_parameters_in)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\mlagents_envs\environment.py", line 601, in send_academy_parameters
    return self.communicator.initialize(inputs)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\mlagents_envs\rpc_communicator.py", line 99, in initialize
    self.poll_for_timeout()
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\mlagents_envs\rpc_communicator.py", line 92, in poll_for_timeout
    "The Unity environment took too long to respond. Make sure that :\n"
mlagents_envs.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Agents are linked to the appropriate Brains
	 The environment and the Python interface have compatible versions.
2020-06-06 00:25:51 ERROR [_server.py:445] Exception calling application: 
Traceback (most recent call last):
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Die Pipe wurde beendet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\grpc\_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\site-packages\mlagents_envs\rpc_communicator.py", line 29, in Exchange
    return self.child_conn.recv()
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\Sebastian\.conda\envs\tensorflow_src_1_14\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError
2020-06-06 00:25:51 INFO [environment.py:498] Environment shut down with return code 0 (CTRL_C_EVENT).
```

**Comment by araffin** [comment]
So, I guess if you try a random agent it will also crash?

```python
from stable_baselines.common.vec_env import DummyVecEnv

def make_env(rank, seed=0):
    """
    Utility function for multiprocessed env.

    :param env_id: (str) the environment ID
    :param num_env: (int) the number of environments you wish to have in subprocesses
    :param seed: (int) the inital seed for RNG
    :param rank: (int) index of the subprocess
    """
    def _init():
        env = UnityToGymWrapper(...) # instantiate your env
        env.seed(seed + rank)
        return env
    return _init

n_envs = 2
n_steps = int(1e5)

env = DummyVecenv([make_env(i) for i in range(n_envs)])

obs = env.reset()
for _ in range(n_steps):
    action = [env.action_space.sample() for _ in range(n_envs)]
    obs, reward, done, info = env.step(action)
```

This looks like an issue with your env, not stable-baselines.

**Comment by pengzhi1998** [comment]
Hi @araffin! Sorry to bother you.
But is it possible to use python multiprocessing directly with a gym-unity environment without applying baseline or stable baseline?

**Comment by Miffyli** [comment]
@pengzhi1998 If I understood you right the question is about using gym-unity environments with multiprocessing, _without_ using baselines/stable-baselines? We do not have answers for this as these issues are for questions related to stable-baselines. You have better luck asking unity gym-unity's repo or elsewhere.

**Comment by pengzhi1998** [comment]
@Miffyli Got it. Thank you for your reply!
