### ISSUE TITLE
Using FrameStack wrapper with Pendulum environment to learn using image stacks as observation

### ISSUE THREAD

**Issue by meric-sakarya** [hill-a/stable-baselines#956]
1) A2C and PPO probably require more samples to learn Pendulum. [Check rl-zoo hyperparameters](https://github.com/araffin/rl-baselines-zoo/blob/master/hyperparams/ppo2.yml#L14), where agent is trained for 2 million steps. Using raw pixels will more-than-likely take longer time to train.

2) You could Atari's [FrameStack wrapper](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/atari_wrappers.py#L197) to stack multiple frames.

_Originally posted by @Miffyli in https://github.com/hill-a/stable-baselines/issues/951#issuecomment-660684374_

As suggested by @Miffyli I am using FrameStack to wrap my Pendulum environment, so I can train my model using image stacks. But the environment checker gives the following error:
```
C:\Users\meric\Anaconda3\envs\pioneer\lib\site-packages\stable_baselines\common\env_checker.py:25: UserWarning: It seems that your observation is an image but the `dtype` of your observation_space is not `np.uint8`. If your observation is not an image, we recommend you to flatten the observation to have only a 1D vector
  warnings.warn("It seems that your observation is an image but the `dtype` "
C:\Users\meric\Anaconda3\envs\pioneer\lib\site-packages\stable_baselines\common\env_checker.py:210: UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html
  warnings.warn("We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) "
Traceback (most recent call last):
  File "C:/Users/meric/OneDrive/Masaüstü/TUM/Thesis/Pycharm/pioneer/pendulum_image_A2C.py", line 70, in <module>
    check_env(pendulum_env, warn=True)
  File "C:\Users\meric\Anaconda3\envs\pioneer\lib\site-packages\stable_baselines\common\env_checker.py", line 214, in check_env
    _check_returned_values(env, observation_space, action_space)
  File "C:\Users\meric\Anaconda3\envs\pioneer\lib\site-packages\stable_baselines\common\env_checker.py", line 99, in _check_returned_values
    _check_obs(obs, observation_space, 'reset')
  File "C:\Users\meric\Anaconda3\envs\pioneer\lib\site-packages\stable_baselines\common\env_checker.py", line 86, in _check_obs
    "method must be a numpy array".format(method_name))
AssertionError: The observation returned by `reset()` method must be a numpy array
```
Any idea what might be causing this error? 
Here is also the code for my custom wrapper:
```
class RGBArrayAsObservationWrapper(Wrapper):
    """
    Use env.render(rgb_array) as observation
    rather than the observation environment provides
    """

    def __init__(self, env):
        super(RGBArrayAsObservationWrapper, self).__init__(env)
        self.reset()
        dummy_obs = env.render('rgb_array')
        dummy_obs_resized = resize(dummy_obs, (dummy_obs.shape[0] // 4, dummy_obs.shape[1] // 4),
                                   anti_aliasing=True)
        # Update observation space
        self.observation_space = spaces.Box(low=0, high=255, shape=dummy_obs_resized.shape,
                                            dtype=dummy_obs_resized.dtype)

    def reset(self, **kwargs):
        obs = self.env.reset(**kwargs)
        obs = self.env.render("rgb_array")
        obs = resize(obs, (obs.shape[0] // 4, obs.shape[1] // 4),
                     anti_aliasing=True)
        return obs

    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        obs = self.env.render("rgb_array")
        obs = resize(obs, (obs.shape[0] // 4, obs.shape[1] // 4),
                     anti_aliasing=True)
        return obs, reward, done, info
```

**Comment by Miffyli** [comment]
Please include the full code that results in the error.

**Comment by meric-sakarya** [comment]
```
import os
import time

import gym
from gym import Wrapper, spaces
import numpy as np
from gym.envs.classic_control import PendulumEnv
from stable_baselines.common.atari_wrappers import FrameStack

from stable_baselines.common.env_checker import check_env
from stable_baselines.sac.policies import CnnPolicy
from stable_baselines import A2C
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.bench import Monitor

from skimage import data, color
from skimage.transform import rescale, resize, downscale_local_mean

import tensorflow as tf


class RGBArrayAsObservationWrapper(Wrapper):
    """
    Use env.render(rgb_array) as observation
    rather than the observation environment provides
    """

    def __init__(self, env):
        # TODO this might not work before environment has been reset
        super(RGBArrayAsObservationWrapper, self).__init__(env)
        self.reset()
        dummy_obs = env.render('rgb_array')
        dummy_obs_resized = resize(dummy_obs, (dummy_obs.shape[0] // 4, dummy_obs.shape[1] // 4),
                                   anti_aliasing=True)
        # Update observation space
        # TODO assign correct low and high
        self.observation_space = spaces.Box(low=0, high=255, shape=dummy_obs_resized.shape,
                                            dtype=dummy_obs_resized.dtype)

    def reset(self, **kwargs):
        obs = self.env.reset(**kwargs)
        obs = self.env.render("rgb_array")
        obs = resize(obs, (obs.shape[0] // 4, obs.shape[1] // 4),
                     anti_aliasing=True)
        return obs

    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        obs = self.env.render("rgb_array")
        obs = resize(obs, (obs.shape[0] // 4, obs.shape[1] // 4),
                     anti_aliasing=True)
        return obs, reward, done, info


# tensorboard --logdir=A2C_IMG_PENDULUM:C:\Users\meric\OneDrive\Masaüstü\TUM\Thesis\Pycharm\pioneer\a2c_pendulum_img_tensorboard --host localhost

log_dir = "/tmp/gym/{}".format(int(time.time()))
os.makedirs(log_dir, exist_ok=True)

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

TEST_COUNT = 100

pendulum_env = gym.make('Pendulum-v0')
pendulum_env = Monitor(pendulum_env, log_dir, allow_early_resets=True)
pendulum_env = RGBArrayAsObservationWrapper(pendulum_env)
pendulum_env = FrameStack(pendulum_env, n_frames=4)
check_env(pendulum_env, warn=True)

model = A2C("CnnPolicy", pendulum_env, verbose=1, tensorboard_log="./a2c_pendulum_img_tensorboard/")
model.learn(total_timesteps=100_000, log_interval=10)
model.save("a2c_pendulum_img")


```

**Comment by meric-sakarya** [comment]
After removing it the code seemed to work. But I can't get good results when working with PPO2 and images. The orange line is from single image frames as observations and the blue one is with FrameStack wrapper. Is PPO2 not good for training with images? What should I change? Is there maybe something wrong with the wrappers? Thanks in advance.
https://ibb.co/G3f1x81

**Comment by araffin** [comment]
>What should I change?

As mentioned by @Miffyli and in the doc (https://stable-baselines.readthedocs.io/en/master/guide/rl_tips.html), you may need to take a look at the zoo and at hyperparameter tuning.

Closing this as the original question was answered.
Note that we don't do tech support.

**Comment by meric-sakarya** [comment]
How can I install RL Baselines Zoo? I am on a windows environment and the installation guide is suited for Linux.

**Comment by Miffyli** [comment]
@meric-sakarya 

This is a rl-zoo issue so you might want to raise it there. You do not need to install the repository per-se, you just need the train/test scripts and the parameters.
