### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by AliBaheri** [hill-a/stable-baselines#99]
Hi,
In Ubunto, i face with the following message after running `pip install stable-baselines`:

`Collecting stable-baselines
  Using cached https://files.pythonhosted.org/packages/80/77/b74fa3c9b26cb71b2f81e09e238ef708a4c1fc30ddd291cdb800270a0a8e/stable_baselines-2.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pV_Zis/stable-baselines/setup.py", line 4, in <module>
        from stable_baselines import __version__
      File "stable_baselines/__init__.py", line 4, in <module>
        from stable_baselines.a2c import A2C
      File "stable_baselines/a2c/__init__.py", line 1, in <module>
        from stable_baselines.a2c.a2c import A2C
      File "stable_baselines/a2c/a2c.py", line 7, in <module>
        from stable_baselines import logger
      File "stable_baselines/logger.py", line 300
        def log(*args, level=INFO):
                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pV_Zis/stable-baselines/`

Can someone please help me what should to do to resolve the issue?

**Comment by AliBaheri** [comment]
Thanks for your prompt response.

Switched to Python 3 and the problem was resolved.
