### ISSUE TITLE
[question] Record a video error

### ISSUE THREAD

**Issue by borninfreedom** [hill-a/stable-baselines#990]
In the [example of recording a video](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#record-a-video), the ```action = [env.action_space.sample()]```,  but now I want to ```action=[model.predict(obs)]``` like the following code:
```python
def make_video(env_id,video_folder,video_length,model):
    """

    :param env_id:
    :param video_folder:
    :param video_length:
    :param model:
    :return:
    """
    from stable_baselines.common.vec_env import VecVideoRecorder, DummyVecEnv
    env=DummyVecEnv([lambda:gym.make(env_id)])

    env=VecVideoRecorder(env,video_folder,record_video_trigger=lambda x:x==0,video_length=video_length,
                         name_prefix="random-agent-{}".format(env_id))
    obs = env.reset()
    for _ in range(video_length+1):
        action=[model.predict(obs)]
        obs,_,_,_=env.step(action)
    env.close()
```
And it will encounter the error, I guess the problem is at ```obs=env.reset()``` and ```action=[model.predict(obs)]```.
```python
Traceback (most recent call last):
  File "C:\Users\born_\anaconda3\envs\workEnv\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a075abc16237>", line 1, in <module>
    runfile('C:/Users/born_/PycharmProjects/test_sb/lunarlander.py', wdir='C:/Users/born_/PycharmProjects/test_sb')
  File "C:\Program Files\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/born_/PycharmProjects/test_sb/lunarlander.py", line 114, in <module>
    make_video(env_id,video_folder,video_length,model)
  File "C:/Users/born_/PycharmProjects/test_sb/lunarlander.py", line 69, in make_video
    obs,_,_,_=env.step(action)
  File "C:\Users\born_\anaconda3\envs\workEnv\lib\site-packages\stable_baselines\common\vec_env\base_vec_env.py", line 150, in step
    return self.step_wait()
  File "C:\Users\born_\anaconda3\envs\workEnv\lib\site-packages\stable_baselines\common\vec_env\vec_video_recorder.py", line 87, in step_wait
    obs, rews, dones, infos = self.venv.step_wait()
  File "C:\Users\born_\anaconda3\envs\workEnv\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 42, in step_wait
    self.envs[env_idx].step(self.actions[env_idx])
  File "C:\Users\born_\anaconda3\envs\workEnv\lib\site-packages\gym\wrappers\time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "C:\Users\born_\anaconda3\envs\workEnv\lib\site-packages\gym\envs\box2d\lunar_lander.py", line 250, in step
    assert self.action_space.contains(action), "%r (%s) invalid " % (action, type(action))
AssertionError: (array([0], dtype=int64), None) (<class 'tuple'>) invalid 
Process finished with exit code 0
```
What's the problem and how to fix it?

**Comment by Miffyli** [comment]
You do not need to wrap `model.predict(obs)` into another list with `[...]`. See the [example below that one](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#bonus-make-a-gif-of-a-trained-agent).

**Comment by borninfreedom** [comment]
> You do not need to wrap `model.predict(obs)` into another list with `[...]`. See the [example below that one](https://stable-baselines.readthedocs.io/en/master/guide/examples.html#bonus-make-a-gif-of-a-trained-agent).

Yeah，recording a gif is OK. And the recording a video case, do you mean to remove the ```[]```? 
I have tried this, it will raise the error (just the last part) :
```python
 File "C:\Users\born_\anaconda3\envs\workEnv\lib\site-packages\gym\envs\box2d\lunar_lander.py", line 250, in step
    assert self.action_space.contains(action), "%r (%s) invalid " % (action, type(action))
AssertionError: array([3], dtype=int64) (<class 'numpy.ndarray'>) invalid 
```

**Comment by Miffyli** [comment]
Note what `model.predict` returns. It does not only return an action but also `states`. It needs to be `action, states = model.predict(obs)`.

**Comment by borninfreedom** [comment]
Oh, yeah, thank you!
