### ISSUE TITLE
[ValueError: could not broadcast input array from shape (3) into shape (58)]

### ISSUE THREAD

**Issue by erebodino** [hill-a/stable-baselines#996]
**Describe the bug**
I'm triying to use A2C on a custom enviroment and this error show up. The error only appers when I tried to stack a few obervations together from a ndarray scaled with StandarScaler. if I don't try to stack the observations and only use one timestep at the time it's works perfectly.

**Code example**

This is the configuration of the enviroment:
```python
self.action_space = gym.spaces.Discrete(n=len(Actions))
self.observation_space = gym.spaces.Box(
            low=-np.inf, high=np.inf,
            shape=((11*self.bars_count)+3,), dtype=np.float32)
```
The reset:
```python
 def reset(self):
        self.have_position = False
        self.long = False
        self.short = False
        self.open_price = 0.0
        self._offset = 0
        self.result_operation = 0
        prices = self._prices
        bars = self.bars_count
        self.account_balance = self.initial_balance
        self.account_balance_unrealized = self.initial_balance
        self.count_steps = 0
        self.rewards_steps = 0
        self.duracion = 0
        self.current_PL = 0
        
        if self.random_ofs_on_reset:
            self._offset = np.random.choice(len(self._prices)- (bars * 2))
        else:
            self._offset = bars
        obs = self.obs_encode(self._prices)
        return obs
```
The obs_encode() method:
```python
def obs_encode(self,prices):
        
            if self.bars_count > 1 :
                res = prices[(self._offset - (self.bars_count - 1)):(self._offset + 1)].to_numpy().flatten()
            else:
                res = np.array(prices[self._offset: self._offset + 1])
            if self.have_position:
                if self.long:
                    res = np.concatenate((res,np.array(float(self.long))),axis=None)
                    res= np.concatenate((res, np.array((self._cur_close() - self.open_price))),axis=None)
                
                elif self.short:
                    res = np.concatenate((res,np.array( - float(self.short))),axis=None)
                    res= np.concatenate((res, np.array((self.open_price - self._cur_close()))),axis=None)
                    
                res = np.concatenate((res,np.array(self.count_steps)),axis=None)
            else:
                res = np.concatenate((res,np.array(0.0)),axis=None)
                res = np.concatenate((res,np.array(0.0)),axis=None)
                res =np.concatenate((res,np.array(0)),axis=None)        
            return res
```

```bash
Traceback (most recent call last):

  File "E:\Anaconda\envs\deepl\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 90, in _save_obs
    self.buf_obs[key][env_idx] = obs

```

**System Info**
Describe the characteristic of your environment:
Spyder IDE, from Anaconda Distribution for Windows.
 * Describe how the library was installed: Installed with pip
 * GPU models and configuration: Only CPU
 * Python version: 3.7.0
 * Tensorflow version: 1.14.0
 * Versions of any other relevant libraries

**Additional context**
In the obs_encode() method i tried to stack the observations with np.append and don´t work either.

I tried everithing listed in the issue #242 and the issue still continues.

**Comment by Miffyli** [comment]
The error message seems to be cut and does not include the full error. Please include the full stacktrace.

Have you taken a look at [FrameStack wrapper]? This one is for images, but should be trivial to extend to different dimensional arrays. Note that if you first create vectorized environment and then apply the wrapper, you need to use [vectorized variant of it](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/vec_env/vec_frame_stack.py#L9).

**Comment by erebodino** [comment]
> The error message seems to be cut and does not include the full error. Please include the full stacktrace.
```
Traceback (most recent call last):

  File "J:\Emma\Cosas_ninja\Chapter10\lib\ES A2C Penalty 2 Sin shift.py", line 581, in <module>
    model.learn(iteraciones, callback=eval_callback)

  File "E:\Anaconda\envs\deepl\lib\site-packages\stable_baselines\a2c\a2c.py", line 261, in learn
    rollout = self.runner.run(callback)

  File "E:\Anaconda\envs\deepl\lib\site-packages\stable_baselines\common\runners.py", line 48, in run
    return self._run()

  File "E:\Anaconda\envs\deepl\lib\site-packages\stable_baselines\a2c\a2c.py", line 360, in _run
    obs, rewards, dones, infos = self.env.step(clipped_actions)

  File "E:\Anaconda\envs\deepl\lib\site-packages\stable_baselines\common\vec_env\base_vec_env.py", line 150, in step
    return self.step_wait()

  File "E:\Anaconda\envs\deepl\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 47, in step_wait
    self._save_obs(env_idx, obs)

  File "E:\Anaconda\envs\deepl\lib\site-packages\stable_baselines\common\vec_env\dummy_vec_env.py", line 90, in _save_obs
    self.buf_obs[key][env_idx] = obs

ValueError: could not broadcast input array from shape (3) into shape (58)


>Have you taken a look at [FrameStack wrapper]? This one is for images, but should be trivial to extend to different dimensional arrays. Note that if you first create vectorized environment and then apply the wrapper, you need to use [vectorized variant of it](https://github.com/hill-a/stable-baselines/blob/master/stable_baselines/common/vec_env/vec_frame_stack.py#L9).

I didn't try. But when I run the script without any wrapper, it's starts training but at some point it crash with that error, so I assume that in that case is not an error on the definition of the custom enviroment.

**Comment by Miffyli** [comment]
> it's starts training but at some point it crash with that error, so I assume that in that case is not an error on the definition of the custom enviroment.

This and the error suggests the environment returns a different observation all the sudden. I suggest you use [environment checker](https://stable-baselines.readthedocs.io/en/master/common/env_checker.html) to make sure the environment works as intended.

**Comment by erebodino** [comment]
Thank you for reply, I started checking my enviroment as you said and i could be able to discover the issue, it was an error on the reset method, when I want to use more than 1 timestep for the observation the starting point sometimes was the first timestep and that generated the error. I just modified that and everything is running ok.
